using System;
using Aiv.Math;

namespace AivRenderer
{
	public class Vertex
	{

		public Vector3 coordinates { get; private set;}
		public Vector2 uv { get; private set;}
		public Vector3 normal { get; private set;}

		// this value is constantly changed by transformations
		// x and y are pixel coordinates, z is the interpolated value
		// generated by the scanline procedure
		public Vector3 projected;

		public Vertex (Vector3 coordinates, Vector2 uv, Vector3 normal)
		{
			this.coordinates = coordinates;
			this.uv = uv;
			this.normal = normal;
		}
	}
}

